# -*- coding: utf-8 -*-
"""CentroidExtraction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WuXyqesVtvAEDVZDrWI4kO2Op9pqcdo-
"""

import xml.dom.minidom

doc = xml.dom.minidom.parse("test2.xml")
#print(doc.firstChild.tagName)

centroids = doc.getElementsByTagName("Spot")

def getlocs(loc_list):
  for pos in loc_list:
    print(pos.getAttribute("POSITION_X") + ", " + pos.getAttribute("POSITION_Y"))

getlocs(centroids)